### ISSUE TITLE
HtmlToText skipping content in select cases

### ISSUE THREAD

**Issue by shailendra735** [keystonejs/keystone-utils#10]
The item description had special characters like this: 

`U.S., Excellent Used Collection, 1861-1920. An nearly complete collection neatly mounted on blank pages; highlights include 1861-66 Issues complete less the 5¢ buff &` **90¢ blue, the 1867 E. grills complete less the
 1¢, the F. grills missing only the 5¢, 15¢ & 24¢ (the 90¢ is repaired but quite attractive), the 1869 Pictorials complete to the 30¢ (plus a mint 1¢and an unused 1¢ reprint #123), the Bank Note
 Issues complete less the grills & Special Printings, the 1890 issue complete, and the Columbians & Trans-Miss. to the 50¢. The First Bureaus include the $1 type I unwatermarked and the $1 type I & $2 watermarked, and the 1902 issue
 is complete to the $5, while the 20th century Commemoratives are complete including the 1909 Lincoln bluish paper. Naturally the highest catalog items have small faults, but they are nearly all quite unobtrusive, and there are plenty of F-VF
 stamps cataloging up to $200 and more;** `plus, there are many, many VF-XF little gems scattered throughout. A really outstanding lot for collector or dealer alike. Scott value is about $19,500. Estimate $4,000 - 6,000.`

And after using htmlToText, this is what I get:

`U.S., Excellent Used Collection, 1861-1920. An nearly complete collection neatly mounted on blank pages; highlights include 1861-66 Issues complete less the 5¢ buff plus, there are many, many VF-XF little gems scattered throughout. A really outstanding lot for collector or dealer alike. Scott value is about $19,500. Estimate $4,000 - 6,000.`

All the **bold** text was skipped. I guess it was because of `&` and `;` forming a combination around the skipped text. 

Any solutions to this?

**Comment by sebmck** [comment]
It's interpreting that part as a single html entity. It looks like the code for [`decodeHTMLEntities `](https://github.com/keystonejs/keystone-utils/blob/5db31fba5c5688711798bea5a0bbcb50ff3b4c80/lib/index.js#L501-503) is too greedy.

**Comment by Benew** [comment]
Other problem, it seems that the decodeHTMLEntities function implementation does not use the String.replace function as it should:

    return str.replace(/&[^;]+;/g, function(match, ent) {
		return String.fromCharCode(ent[0] !== '#' ? htmlEntities[ent] : ent[1] === 'x' ? parseInt(ent.substr(2),16) : parseInt(ent.substr(1), 10));
	});

The second parameter will be an offset of the match, not the entity itself since no capturing parenthesis are present in the regex.

I'll make a commit on my fork and ask for a merge replacing the regex with `/&([^;]+);/g`

**Comment by Benew** [comment]
@shailendra735 PR #16 should fix your problem. Can you test it please? Your input would be valuable.

**Comment by JedWatson** [comment]
Should be fixed by @Benew's latest PR. Published as `v0.2.1`.
