### ISSUE TITLE
Tests breaking with new `limax` integration

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone-utils#12]
@lovell - wondering if you're interested in looking at this / commenting

Our tests for this library are currently failing because the conversions have changed, including some that seem like regressions:

```
AssertionError: "one2-three" must equal "one-2-three"
AssertionError: "the-user-s-guide" must equal "the-users-guide"
```

... and some I am not qualified to say which version is better:

```
AssertionError: "ce-diaz-ue" must equal "ce-diaz-u"
AssertionError: "kak-upoitelny-v-rossii-vechera" must equal "kak-upoytelny-v-rossyy-vechera"
```

**Comment by lovell** [comment]
Hi Jed,

I'll need to dig a little deeper to understand why the first one is wrong, and for the second we'll need to add support to limax for [smart quotes](https://github.com/keystonejs/keystone-utils/blob/master/tests/strings.js#L151). Leave them with me.

I believe limax's `Ü` to [Ue](http://en.wikipedia.org/wiki/%C3%9C#U-umlaut) and `и` to [i](http://en.wikipedia.org/wiki/Romanization_of_Russian#Transliteration_table) transliterations are both correct.

**Comment by JedWatson** [comment]
As of the recent upgrade to `limax` all tests are passing again, so I'll push out a new release with all the updates! Thanks for all your work on this @lovell.
