### ISSUE TITLE
Error installing 0.2.0 on Azure (0.1.13 Works)

### ISSUE THREAD

**Issue by shauntrennery** [keystonejs/keystone-utils#15]
Application has thrown an uncaught exception and is terminated:
Error: Cannot find module './build/Release/cld'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\keystone-utils\node_modules\limax\node_modules\cld\index.js:2:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by JedWatson** [comment]
`cld` is a dependency of the new package we're using to generate slugs, `limax`. Looks like it is having issues on Azure...

Sorry for the delay responding, @shauntrennery have you learned anything since posting this issue? maybe we should open an issue on one of those projects, I don't have a lot of experience with why this would be failing.

**Comment by shauntrennery** [comment]
@JedWatson unfortunately not. Not had too much time to dig deeper. I'm relying on 0.1.13 for now.

**Comment by JedWatson** [comment]
We use Heroku for simple hosting cases, or build our own AWS configs for more complicated setups where we want control over hardware / load balancers / etc.

Definitely don't want to block using Azure as a host though. Unfortunately I also don't have a Windows development machine handy, do you know if the build works on Windows?

**Comment by shauntrennery** [comment]
Sorry, not proving to be much help. I'm a Mac user myself.

**Comment by JedWatson** [comment]
No problem. I'll see what I can do to follow this up.

**Comment by lovell** [comment]
`limax` v1.1.2 removed `cld` as a dependency.

**Comment by JedWatson** [comment]
Thanks @lovell! @shauntrennery this should mean everything's resolved. I'll publish a new version of `keystone-utils` with an updated dependency, can you let me know if it works now?

**Comment by shauntrennery** [comment]
@JedWatson Many thanks. I'll include the new version in my next deployment and update this accordingly.

**Comment by shauntrennery** [comment]
Deployed version 0.2.2 to our Azure production site last night and all is working as expected. Many thanks.

**Comment by JedWatson** [comment]
Great :)
